#!/usr/bin/env bash
# Displays "To infinity and beyond" indefinitely with
# a sleep 2 in between each iteration.
# Displays "I am invincible!!!" in between each iteration.

# Function to handle SIGTERM signal
function handle_sigterm {
  echo "I am invincible!!!"
  exit 0
}

# Set up trap for SIGTERM
trap 'handle_sigterm' SIGTERM

while true
do
  echo "To infinity and beyond"
  sleep 2
  echo "To infinity and beyond"
  sleep 2
  echo "I am invincible!!!"
done
