#!/usr/bin/env bash
# This script is displaying "Best School" 10 times but for te 9th iteration display "Hi" on a new line

number_count=1

while [ $number_count -le 10 ]
do
	echo "Best School"
	if [ $number_count -eq 9 ]
	then
		echo "Hi"
	fi
	((number_count++))
done
