#!/usr/bin/env bash
# This script that loops "Best School" from 1 to 10 and "bad luck", "good luck" for the 4th and 8th iteration respectively

number_count=1

while [ $number_count -le 10 ]
do
    if [ $number_count -eq 4 ]
    then
        echo "bad luck"
    elif [ $number_count -eq 8 ]
    then
        echo "good luck"
    else
        echo "Best School"
    fi
    ((number_count++))
done
